### ISSUE TITLE
Android support missing.

### ISSUE THREAD

**Issue by Joachim26** [Sopel97/FatTitz#9]
You didn't yet apply your 'Optimize FT activation and affine transform for NEON' patch. Will there be Android support in the final version of Fat Titz 2.0? If yes, that would be great! Thanks in advance!

**Comment by Sopel97** [comment]
That patch wouldn't apply here as it uses a different algorithms to accomodate the large layer. Though I can see a need for NEON now more than before as it would also allow it to run on Apple M1. Considering that there's a lot algorithmic differences compared to Stockfish that would require different NEON code, and I'm not sure how well NEON can do here, but I'll take a look at it.

**Comment by Joachim26** [comment]
Thanks Tomasz for having a look at it. When I saw this neon patch last week, and your hint on FT2.0 to Alex, I assumed that neon support for FTv2.0 isn't a big deal. But I don't have the necessary technical background. An alternate way, maybe easier to implement, would be for Android and Apple M1 users, support for the current half_ka_v2_hm net architecture. In other words a new updated CFish branch in addition to the Fat CFish/Titz v2.0 branch. I'm just thinking loud...don't take it too serious. Best regards
